assets:
    js:
        app:
            - jquery-1.11.3.min.js
            - bootstrap.min.js
            - app.js
        admin:
            - jquery-1.11.3.min.js
            - bootstrap.min.js
            - ../../../../../vendor/cregnier/agile-admin-bundle/Resources/js/admin-theme.js
            - ../../../../../web/bundles/agileadmin/plugins/select2/select2.min.js
            - ../../../../../web/bundles/agileadmin/plugins/iCheck/icheck.min.js
            - ../../../../../web/bundles/agileadmin/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.js
