# FOSUserBundle Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    use_username_form_type: false
    user_class: AppBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    registration:
        confirmation:
            enabled: true
            template:   app/mail/email_registration.html.twig
        form:
            type: AppBundle\Form\Type\RegistrationType
    resetting:
        email:
            template:   app/mail/email_resetting.html.twig
    profile:
        form:
            type: AppBundle\Form\Type\ProfileFormType
    from_email:
        address: '%no_reply_email%'
        sender_name: '%no_reply_sender%'