# Liip Imagine Filters
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        header_logo:
            quality: 75
            filters:
                thumbnail: { size: [160, 124], mode: outbound }
        profil_picture_header:
            quality: 75
            filters:
                thumbnail: { size: [75, 55], mode: outbound }
        social_icon:
            quality: 75
            filters:
                thumbnail: { size: [40, 40], mode: outbound }
        article_picture_admin :
            quality : 75
            filters :
                thumbnail: { size : [200, 150], mode : outbound }
        property_list:
            quality : 75
            filters :
                thumbnail: { size : [200, 150], mode : outbound }
        property_list:
            quality : 75
            filters :
                thumbnail: { size : [200, 150], mode : outbound }
        property_item:
            quality : 75
            filters :
                thumbnail: { size : [357, 369], mode : outbound }
        property_small_item:
            quality : 75
            filters :
                thumbnail: { size : [120, 90], mode : outbound }
