# Liip Imagine Filters
liip_imagine:
    resolvers:
       default:
          web_path: ~
    filter_sets:
        cache: ~
        header_logo:
            quality: 75
            filters:
                relative_resize:
                    heighten: 100
