services:
    app.security.login_success_handler:
        class:      AppBundle\Security\Authentication\Handler\LoginSuccessHandler
        arguments:
            - "@router"
            - "@security.authorization_checker"
