services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        arguments:
            - '@translator.default'
        tags:
            - { name: twig.extension }

    twig.extension.html:
        class: AppBundle\Twig\HtmlRawSafeExtension
        tags:
            - { name: twig.extension, alias: twig_extension_html }

    app.extension.page:
        class: AppBundle\Twig\PageExtension
        arguments:
            - '@doctrine.orm.entity_manager'
        tags:
            - { name: twig.extension }

